#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

if [ -f .sdkmanrc ]  && [ -f "$HOME/.sdkman/bin/sdkman-init.sh" ]; then
  # Execute sdk env command
  # Load sdkman
  source "$HOME/.sdkman/bin/sdkman-init.sh"

  # Execute sdkman commands
  sdk env
fi

npx lint-staged --verbose --debug